version: '3.8'

services:
  financial-streams:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: financial-streams
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - ENV=production
      - LOG_LEVEL=info
    volumes:
      - ../data:/data
      - ../logs:/logs
    networks:
      - financial-network

  # Redis for caching and pub/sub
  redis:
    image: redis:7-alpine
    container_name: financial-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - financial-network

  # PostgreSQL for persistent storage
  postgres:
    image: postgres:15-alpine
    container_name: financial-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=financialstreams
      - POSTGRES_USER=fsuser
      - POSTGRES_PASSWORD=fspassword
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - financial-network

networks:
  financial-network:
    driver: bridge

volumes:
  redis-data:
  postgres-data: